### ISSUE TITLE
kerberosio says "Illegal instruction"

### ISSUE THREAD

**Issue by sabaatworld** [kerberos-io/machinery#108]
I have installed everything using the RPi guide on my RPi 0 W. The server works but says that machinery is not running. When I ssh into RPi and run kerberosio it prints "Illegal instruction" and exits.

Any idea what is wrong?

**Comment by cedricve** [comment]
Hey, can you try to manually run the machinery by writing the "kerberosio" command?

**Comment by cedricve** [comment]
Can you debug with *gdb*?

    gdb kerberosio

**Comment by projetsdiy** [comment]
I've the same problem (RPi Zero). The error returned by gdb is 
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0xb6d38b10 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0

Hope it will useful

**Comment by cedricve** [comment]
will be fixed with #109
