### ISSUE TITLE
SSL version 1.0.0 is no longer accessible in Raspbian

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/machinery#109]
Make sure the machinery is compiled with the new version of SSL.

**Comment by cedricve** [comment]
Fix will be included in next release.

**Comment by cedricve** [comment]
fixed in KiOS v2.5.0, Machinery v.2.4.0

**Comment by marciano1** [comment]
Just installed in RPi Zero W from https://doc.kerberos.io/2.0/installation/Raspbian and ssh.
`kerberosio`     
Illegal instruction
`gdb kerberosio`     
> Reading symbols from kerberosio...done.
> (gdb)

**Comment by cedricve** [comment]
Which .deb file did you installed?

**Comment by marciano1** [comment]
Sorry, I have several Pis, I replaced X by 3 and I should replaced it by ...? I tried Z and z.

**Comment by cedricve** [comment]
@marciano1, I have updated the documentation. I hope it's more clear which version you should download.
