### ISSUE TITLE
Pause for x seconds after detection

### ISSUE THREAD

**Issue by loki-sft** [kerberos-io/machinery#110]
Is it possible to stop the heuristic for a given time after a detection.
I using a push service to get a notification on my mobile phone for every incident in my backyard.
Most of the time its just my cat comming home and walking around. 
I want to see just the first image and than wait some time for the next detection.

**Comment by cedricve** [comment]
fixed in KiOS v2.5.0, Machinery v.2.4.0. You can use the new throttling attribute.
