### ISSUE TITLE
Docker Autoremoval script specifies non-existant device

### ISSUE THREAD

**Issue by ross-w** [kerberos-io/machinery#116]
The autoremoval script in [run.sh](https://github.com/kerberos-io/machinery/blob/master/docker/run.sh#L7) greps for the device `/dev/vda1`.

This device does not exist on my Docker system (I assume it is related to both the storage driver and underlying device.) Therefore, the autoremoval script fails to do anything.

Could it instead check the device related to the capture directory? You can pass this into df and it seems to give back the correct device. If so, I'd propose changing:
```
if [[ $(df -h | grep /dev/vda1 | head -1 | awk -F' ' '{ print $5/1 }' | tr ['%'] ["0"]) -gt 90 ]];
```
to
```
if [[ $(df -h /etc/opt/kerberosio/capture | tail -1 | awk -F' ' '{ print $5/1 }' | tr ['%'] ["0"]) -gt 90 ]];
```

Thoughts?

**Comment by cedricve** [comment]
Hmm, interesting let's create a PR on the https://github.com/kerberos-io/machinery/docker directory.
