### ISSUE TITLE
KiOS IP Cam Config Timezone Resets to Default

### ISSUE THREAD

**Issue by dannyzumwalt** [kerberos-io/machinery#125]
New install on RPi B. The camera configuration web interface will not let me change timezone from default "Europe/Brussels +02:00". I am trying to set it to America/Denver -06:00 and have also tried other cities, but after clicking Update, the timezone always resets to Brussels. All my timestamps show the wrong timezone because of this. Tried rebooting. I see this issue was brought up in the past with a fix to timezone.blade.php, and I confirmed my timezone.blade.php file has the updated code, but still the issue persists.

**Comment by dannyzumwalt** [comment]
Oops, I'll move this to /web

**Comment by cedricve** [comment]
moved to kerberos-io/web#109
