### ISSUE TITLE
Can't install from Armibian 

### ISSUE THREAD

**Issue by joehk2017** [kerberos-io/machinery#127]
Hello , 

I have problem with when i installed armbian-machinery-kerberosio-armhf-2.4.0.deb   file  and systemctl enable kerberosio && reboot then can't run kerberosio and  the binary from /usr/bin/kerberosio folder No such file or directory said me haven't libcurl.so.4 and libavcodec.so.56 , but i have installed libcurl3 pkg-config libavcodec-dev libavformat-dev libswscale-dev . 

How can i fix this ?

Thank !

**Comment by cedricve** [comment]
Hey @joehk2017,

Hmm might require a new build of the armbian deb file.
We'll work on this.

Cédric

**Comment by cedricve** [comment]
WIP @ https://github.com/kerberos-io/machinery/issues/134
