### ISSUE TITLE
Add background color timestamp 

### ISSUE THREAD

**Issue by op3nus3r** [kerberos-io/machinery#128]
Hello everyone, thank you for this excellent application which I use with great pleasure on my Raspberry Pi 3. 
I use timestamping to mark captured images, during the day the image is white and the timestamping is written in black, everything is fine. 
During the night the image is black and the timestamp is always black, so you don't see it.
Is it possible to add a color background to the timestamp?

**Comment by cedricve** [comment]
hey @op3nus3r, what I usually do is setting the timestamp color to red..

**Comment by op3nus3r** [comment]
Hello @cedricve , thank you for your answer. 
That's what I also do, I added the red for the time stamp. I tried a little bit of every color. Under certain conditions, when the sun sets on a white wall or with yellow public lighting, the red timestamp is difficult to read as well.
It was just a suggestion to be able to configure a background color for timestamping if needed, it's not essential I thought I might not be the only one in this situation.

**Comment by cedricve** [comment]
makes sense @op3nus3r, I think we'll add a background color by default then.. Let me assign a label to it, and add it to our next release.

**Comment by op3nus3r** [comment]
Thank you very much for your answers, I don't doubt that this will be useful to a lot of people.

**Comment by cedricve** [comment]
will be available in next release @op3nus3r, thanks for sharing!
