### ISSUE TITLE
Error on fresh installation of KiOS for Pi3 vB (Broadcom.Camera.Module) and infinte loop in boot

### ISSUE THREAD

**Issue by 8ternity** [kerberos-io/machinery#132]
I download a fresh installation IMG of Kios and install on the SD Card. Everything was booting normaly except the internal Broadcom Camera module are crashing and KiOS are rebooting infintly from the machinery section.

Is that a fix for that?

**Comment by cedricve** [comment]
@8ternity, make sure you have a Raspberry Pi camera connected or change the device type through the settings page (USB/IP camera).

**Comment by gregorredinger** [comment]
@cedricve Thanks a lot, i had the same issue, because i use an usb cam instead of a raspberry cam.  changing the value in settings from RasperryCamera to USBCamera fixes the problem.

**Comment by cedricve** [comment]
correct @gregorredinger, thanks for sharing!

**Comment by Bechrissed** [comment]
Where do I change this setting? I just downloaded the installer and i'm never asked for a RaspberryCamer or USBCamera. I also see no file to edit after flashing.
