### ISSUE TITLE
No v2.6.0 tagged release

### ISSUE THREAD

**Issue by d4l3k** [kerberos-io/machinery#140]
Hi, I noticed on the website it says that v2.6.0 has been released and there are release notes for it on the docs repo https://doc.kerberos.io/2.0/release_notes. However, there isn't a tagged release for it in this repo.

I'm using https://aur.archlinux.org/packages/kerberosio-machinery/ which uses the tagged releases to build from.

**Comment by cedricve** [comment]
hey @d4l3k, v.2.6.0 is the version of KiOS. The machinery and web are both on v2.5.0. So this looks like latest version. Btw thanks for sharing the link, wasn't aware of this AUR package.
