### ISSUE TITLE
Problems installing the Generic version on Ubuntu

### ISSUE THREAD

**Issue by ThomasDebnt** [kerberos-io/machinery#143]
Hi !

I always get the same mistake when I try to install the Generic version on Ubuntu and I don't know what to do. Any ideas how to unlock the situation?
Thank you! 

![2018-04-17_10-44-27_virtualbox](https://user-images.githubusercontent.com/38457580/38859087-8e86a47e-422d-11e8-8cf5-110e56987582.png)

**Comment by cedricve** [comment]
hi make sure you have openssl installed.

**Comment by ThomasDebnt** [comment]
it was installed !

**Comment by drphil3d** [comment]
I ran into the same exact issue

**Comment by pr3wtd** [comment]
Same here, Ubuntu 16.04

**Comment by cedricve** [comment]
Try this

    apt-get install libssl-dev

**Comment by cedricve** [comment]
Someone, any update if this resolved the issue?

**Comment by pr3wtd** [comment]
Yes, thank you, it works 👍
