### ISSUE TITLE
Killing gracefully without video corruption

### ISSUE THREAD

**Issue by spaceneedle** [kerberos-io/machinery#146]
Hello,

I am using a Pi button shim for controlling Kerberos. One of the functions is to stop the stream so the SD card can be unmounted. However, when I issue a kill command, the software abruptly stops and the video file becomes corrupted. 

Does Kerberos respond to a special signal to quit gracefully? Are there any other techniques advised to cause Kerberos to quit?

Thanks,
Casey

**Comment by cedricve** [comment]
hey @spaceneedle sounds cool! Yes you can disable the system first before killing it. This will make sure it stops recording properly after a few seconds. 

You can disable it by using the REST API (https://doc.kerberos.io/2.0/web/aPI) or updating the config files.
