### ISSUE TITLE
Install over OpenWRT

### ISSUE THREAD

**Issue by gazambuja** [kerberos-io/machinery#15]
I can install OpenCV, PHP, python, etc over Openwrt, its possible install machinery in this plataform?

**Comment by cedricve** [comment]
I think that should be possible. You should give it a try, keep us posted.

**Comment by cedricve** [comment]
@gazambuja do you have experience with this?

**Comment by gazambuja** [comment]
I use and install hundred devices with openwrt, but I not try install or make machinery.

**Comment by cedricve** [comment]
You can follow the debian image to install the machinery. https://doc.kerberos.io/2.0/installation/Raspbian

Not sure if this is enough?
