### ISSUE TITLE
Add support for client_id in MQTT

### ISSUE THREAD

**Issue by dimaj** [kerberos-io/machinery#151]
Current implementation of `IoMQTT` does not support users to provide a custom `client_id`. 

The way I have my mosquitto server setup is that it requires all clients to have a specific prefix for a client_id. This makes the setup a little more secure in my opinion. 
Based on what I've seen in the code, the only things are are configurable are credentials, connection encryption, server host/port and topic.

Based on what I've seen, I'm guessing prefix is configured via constructor for `mosquittopp` 
 * https://github.com/eclipse/mosquitto/blob/master/lib/cpp/mosquittopp.cpp#L168-L170
 * https://github.com/eclipse/mosquitto/blob/5e60136449d678948520085985d7e7f91f9e601c/lib/mosquitto.h#L197...L203

**Comment by dimaj** [comment]
After reading code some more, mosquitto is reinitialized with a client ID set to camera name. It would still be awesome if there was a separate field for client id, which would default to camera name if field is left blank

**Comment by cedricve** [comment]
hmm @dimaj, looks like i've closed your PR because it was still pointing to master. Can restart your PR with the correct branch?

**Comment by dimaj** [comment]
my PRs have been merged. This issue could be closed.
