### ISSUE TITLE
Move S3 upload to machinery and remove sync-s3 repository

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/machinery#16]
For performance and architectural reasons, the uploading of images to a S3 bucket should be managed by the machinery and not longer exists as a separate service ([sync-s3](https://github.com/kerberos-io/sync-s3)).

We will need to use the [AWS C++ library](https://github.com/awslabs/aws-sdk-cpp/tree/master/aws-cpp-sdk-s3), and run a seperate thread in the machinery that will upload images to the S3 bucket. 

Following features are needed
* Upload image to a S3 bucket
* When no connection is available, images needs to be synced at a later time, when the connection is back online.
* Uploading images has a lower priority than the image processing itself, this means that if the machinery is detecting motion and saving images, the sync-thread should halt or release it resources to the image processing.

**Comment by nicolas-f** [comment]
If cloud is not configured the process should not be started.

**Comment by cedricve** [comment]
Did some research on how to do it in C++: https://blog.cedric.ws/how-to-use-aws-with-your-c-application.
I will soon try to implement this in the machinery.

**Comment by cedricve** [comment]
Feature added to develop branch
