### ISSUE TITLE
What to run on Raspi with pi camera?

### ISSUE THREAD

**Issue by wicadmin** [kerberos-io/machinery#165]
So, I understand the architecture a bit and would like to run the the raspi and pi camera module in an enclosure but not run the machinery and web on it (it is a first gen pi Model A 256MB). I prefer to run those on docker on a central server. What is recommended to run on the Pi to make it enough of an IP cam to talk to the docker components on a central docker server?

**Comment by cedricve** [comment]
Interesting, you should convert the raspberry pi camera to a RTSP stream, afterwards you'll be able to enter stream url into kerberos.io

http://www.raspberry-projects.com/pi/pi-hardware/raspberry-pi-camera/streaming-video-using-vlc-player

**Comment by wicadmin** [comment]
@cedricve - very good. I assume this is the best option for this board? I have several as I had bought them a while back (several years) to use a security cameras. I was following [this](https://github.com/silvanmelchior/RPi_Cam_Web_Interface) and it runs well but now would like to give kerberos.io a go instead.

With the above setup, I assume this means that data would continuously be streaming. How much Mbps do you estimate with 1080p resolution? When I thought about this, then I think it was better to run the machinery and web on the Pi but concern how it would run on it if at all?

**Comment by wicadmin** [comment]
I'm receiving this error:
`06/09/2018 22:51:40.892 ERROR [trivial] OpenCV : can't open url of ip camera`

**Comment by wicadmin** [comment]
OK, I have had success with [v4l2rtspserver](https://github.com/mpromonet/v4l2rtspserver). I wrote a [wiki page](https://github.com/mpromonet/v4l2rtspserver/wiki/Setup-on-Pi) there on my setup to auto start etc.

**Comment by cedricve** [comment]
cool thanks for sharing! would you mind to contribute to our documentation repo? https://github.com/kerberos-io/documentation

**Comment by wicadmin** [comment]
No worries. It can be contributed.

**Comment by wicadmin** [comment]
PR #12 create. 
Add documentation for RTSP server #12

Thanks.
