### ISSUE TITLE
What are the TCP connections for?

### ISSUE THREAD

**Issue by eisenhowerj** [kerberos-io/machinery#199]
**Describe the bug**
What are these two TCP connections for? 

`kerberosi 133 root   10u  IPv4           25197233      0t0      TCP kerberos.localdomain:38238->104.28.6.92:https (ESTABLISHED)`

`kerberosi 133 root   13u  IPv4           25947336      0t0      TCP kerberos.localdomain:52044->159.65.215.225:1883 (ESTABLISHED)
`

**Operating System and Device (please complete the following information):**
 - Host system: systemd-nspawn container (generic build from source)
 - OS: debian8
 - Installation Method: Generic

**Comment by cedricve** [comment]
the first one is a legacy one to make sure the wifi connections stays up for IP cameras (it's just polling an endpoint).

the proxy is for cloud users to give extra capabilities (turn off devices, monitoring usage, etc).
