### ISSUE TITLE
Browser notification can't be disabled!

### ISSUE THREAD

**Issue by jackstuard** [kerberos-io/machinery#223]
**Describe the bug**
Notifications are always enabled, and the speech api can't even be disabled by chrome "mute tabs"
Please allow it to be disabled.

**To Reproduce**
1. Go to main screen and wait.

**Expected behavior**
Disable toggle really disable that speech synthesis notifications

**Screenshots**

**Operating System and Device (please complete the following information):**
 - Host system: Linux VM, Raspberry Pi Version: [0, 1, 2, 3]
 - OS: KiOS, Raspbian, Docker, Ubuntu, CentOS, ..
 - Installation Method: KiOS installer, Etcher, Generic Installation, Docker

**Additional context**

**Comment by cedricve** [comment]
@jackstuard you have to go to the livestream page, and press the voice toggle at the right bottom. We will make that clear in the next version of Kerberos Cloud.

**Comment by jackstuard** [comment]
That works! Thank you!
Please maybe tie with this option, it will be more clear:
![image](https://user-images.githubusercontent.com/39929877/108558944-edaf2100-72fa-11eb-9db0-0246f426e510.png)

**Comment by cedricve** [comment]
Good point thank you @jackstuard
