### ISSUE TITLE
Execute multiple kerberos instance on a machine

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/machinery#24]
It would be helpfull, if multiple camera's can be processed on a single machine. Therefore it should be possible to run one or more instances.

To make this possible a user should be able to pass parameters which can override the exisiting configuration files.

E.g.

```
kerberosio --capture IPCamera --captures.IPCamera.url rtsp://camera1--name ipcamera1

kerberosio --capture IPCamera --captures.IPCamera.url rtsp://camera2--name ipcamera2

kerberosio --capture IPCamera --captures.IPCamera.url rtsp://camera3--name ipcamera3
```

**Comment by cedricve** [comment]
fix added to develop branch 

https://github.com/kerberos-io/machinery/commit/968db17e3e4d7a7375155c59fb187d5b655f4c64

**Comment by marksev1** [comment]
I don't understand something from the docs...If I would have multiple cameras set up, could I still view them all in the WebUI and see events of all of them there?

**Comment by cedricve** [comment]
Yes, that's correct. All images will be shown in the web interface.

**Comment by marksev1** [comment]
In the same web interface? Or would one have to know the specific IP address of each camera, to invoke each different webui?
If its not in the same interface can you make tabs in the webui to switch between various cameras?

**Comment by cedricve** [comment]
This topic is about multiple camera's on the same machine. Your question is different: can I view images of multiple machines in one web interface. 

We have created a cloud application to solve this problem (https://cloud.kerberos.io). The idea is that you subscribe to a plan, and configure every machines with some credentials, and from then they will sync images to our cloud application.

**Comment by muten84** [comment]
Each machinery instance can manage 1 camera and the web ui can read an image folder and can manage config files of a single instance.
