### ISSUE TITLE
New repository: Pilot

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/machinery#25]
A new repository will be created, named Pilot (other names are welcome). The Pilot project will provide a GUI in the terminal, to start and monitor multiple kerberos instances (multiple machinery running). This will allow us to control one or more camera's on a single Raspberry Pi.

- [ ]  Create a first mockup of the GUI.
- [ ]  Implement ONVIF standard to locate IP camera's available on the network.
- [ ]  Define one or more IP camera's, USB camera or Raspberry Pi Camera (and specify additional configuration, e.g. RTSP url).  
- [ ]  Run a machinery process for each camera with there specific configuration.
- [ ]  Show a real-time view of all the machinery processes running (memory consuming, etc)
- [ ]  more to come ..

**Comment by Orabig** [comment]
This idea has been cancelled ?

**Comment by cedricve** [comment]
I don't have the time right now, and @mazki516 is working for a client. I think I will redesign the machinery and web to handle multiple instances. Future work..
