### ISSUE TITLE
What is the history of this project?

### ISSUE THREAD

**Issue by marktheunissen** [kerberos-io/machinery#3]
Hey there. I installed this tonight and messed around, got it capturing some images. Everything looks very slick, must have been a lot of work. How many people are involved? Is it a company or private individual? Is it funded?

**Comment by cedricve** [comment]
Hello Mark. Until now the project have been a one-man show. I've been developing for one year on Kerberos.io. For the moment it's just an open source product, managed by myself. So the project is not a company but a private individual. It's not funded at the moment.
