### ISSUE TITLE
IO - run arbitrary script/program

### ISSUE THREAD

**Issue by discoduck2x** [kerberos-io/machinery#31]
I want to hook onto gammu to send txt messages , now i cant see how to do that currently?
(unless i just trigger by image creation outside of kerberos)

**Comment by cedricve** [comment]
For the moment not possible, we'll need to add a new IO device, which gets as parameter the path to a script.

**Comment by marksev1** [comment]
Events are sent via Webhooks right? Maybe you could tie that with your service for sending msg's discoduck2x?

**Comment by discoduck2x** [comment]
@marksev1 that means one more thing inbetween , need something to listen for the weebhook post and then have that trigger script/gammu sms process..... just let it run any arbitrary script with stuff as variables imgs etc....

**Comment by cedricve** [comment]
feature has been added to develop branch, and will be integrated in version 2.2.0
