### ISSUE TITLE
Add timestamp to the images

### ISSUE THREAD

**Issue by Orabig** [kerberos-io/machinery#36]

**Comment by cedricve** [comment]
This should be an option in the configuration files, which can be enabled/disabled. @Orabig is there a preferred location for the timestamp? Left-top or right-bottom?

**Comment by Orabig** [comment]
Well, I don't think it matters a lot.
I just made some research, and it seems the timestamps can be in any of the corners.

**Comment by cedricve** [comment]
User can now check an option if he want to mark the images with a timestamp (timezone taken into account) + the color of the timestamp. Location is always left top. If needed we can make this configurable as well in the future.

![timestamp-on-image](https://cloud.githubusercontent.com/assets/1546779/15860307/cd11cd44-2cc8-11e6-968f-a0fd4125e09f.PNG)
