### ISSUE TITLE
Expositor: multiple regions

### ISSUE THREAD

**Issue by muten84** [kerberos-io/machinery#37]
It would be useful to have an expositor for configuring more than one region. The behavior could be like the Hull Expositor to paint N rectangles on the image. This kind of expositor should help to monitor many sub-regions, for outdoor surveillance context and to avoid monitoring of non sensible areas, such as pedestrians passage.

**Comment by cedricve** [comment]
I've been thinking about this and basically you can fake it with one simple expositor. See my image blow. I don't see a huge benefit in function of the development effort that is required to create this.

What do you think @muten84 ?

![screen shot 2016-06-07 at 16 10 56](https://cloud.githubusercontent.com/assets/1546779/15860715/7b2ff0f8-2cca-11e6-9176-feb144ef0278.png)

**Comment by muten84** [comment]
Great! It should be ok. Let me try this approach with my scenarios so I can check it.

**Comment by muten84** [comment]
Tried on latest stable version: it works!
