### ISSUE TITLE
Features Next Release?

### ISSUE THREAD

**Issue by noxx2015** [kerberos-io/machinery#49]
Hello

kerberos looks fine, but

- why i cant save video streams?
- why i cant see my streams only with chrome?
- why i cant use more as one cam?

is it possible to add this in the next release?

**Comment by cedricve** [comment]
Hello noxxx

- We will integrate the functionality to save videos to disk (currently only images).
- This is a bug, we will solve this in next release 2.1.0
- This will make the system more complex, and we don't want this :) It should be as atomair as possible. When managing multiple devices, you can still spawn multiple kerberosio threads by overriding the commandline options. The way to go is docker of course, which runs a container for each camera.

Hope this helps..
