### ISSUE TITLE
IO device: webhook

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/machinery#5]
Implement `IoWebhook`, send post request to a specific URL.

**Comment by marksev1** [comment]
Questions:

When does webhook get triggered? (when motion is detected?)

What does the json contain?

**Comment by cedricve** [comment]
Hmm should add this to the documentation at IoWebhook. For the moment of writing you can find it at the Counter Heuristic: https://doc.kerberos.io/2.0/machinery/heuristics/counter.

And yes everytime an image is save it will post to the webhook.

**Comment by marksev1** [comment]
Nice, yup I see it, nice.
