### ISSUE TITLE
service hangs after few hours

### ISSUE THREAD

**Issue by NicoVermeir** [kerberos-io/machinery#50]
I'm not sure if this is the correct repo to report this issue.

I installed KerberosIO on Raspbian (rpi2), it works fine with a usb webcam, but after a few hours the feed is not available anymore and I need to restart the service. The log doesn't tell me anything either, last entry is "Starting stream on port 8888"

**Comment by cedricve** [comment]
Hello Nico

Did you enable verbose logging already?

**Comment by NicoVermeir** [comment]
Hi Cedric,

just switched it on, I'll keep an eye on it. thanks

**Comment by NicoVermeir** [comment]
well, it happened again. this is in the logs:
![image](https://cloud.githubusercontent.com/assets/3177418/17971217/299c1b38-6ada-11e6-9386-810169ef18e8.png)

extra info: I have not changed anything in the config, only switched to usb camera and that was it

**Comment by cedricve** [comment]
Thank you Nico, can you attach the config.xml and condition.xml

**Comment by NicoVermeir** [comment]
here you go
[configs.zip](https://github.com/kerberos-io/machinery/files/437163/configs.zip)

**Comment by cedricve** [comment]
Thanks, is there a reason why you've changed "Enabled" to false in the condition.xml?

**Comment by NicoVermeir** [comment]
I haven't changed anything in the condition settings AFAIK

**Comment by cedricve** [comment]
Hmmm, I will check this. Can you change it back to true, and see if the problem still occurs?

**Comment by NicoVermeir** [comment]
will do!

**Comment by NicoVermeir** [comment]
the issue is still there, but this time the log looks like this:
![image](https://cloud.githubusercontent.com/assets/3177418/17995208/27ff6d08-6b60-11e6-9df5-0298c23af4f9.png)

**Comment by cedricve** [comment]
Hmm, interesting. Please attach the complete log file.

**Comment by NicoVermeir** [comment]
[log.zip](https://github.com/kerberos-io/machinery/files/438623/log.zip)

**Comment by cedricve** [comment]
@NicoVermeir can you try with latest version?

**Comment by NicoVermeir** [comment]
seems to be resolved. thanks!
