### ISSUE TITLE
build fail in raspbian jessie

### ISSUE THREAD

**Issue by ypwu1** [kerberos-io/machinery#51]
Build failed in installation step as following:

`pi@raspberrypi:~/machinery/build $ cmake .. && make && make check && sudo make install
External project: Googletest
External project: OpenCV
Bind project: Userland
External project: RaspiCam
External project: Restclient
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/machinery/build
[  8%] Built target googletest
[ 16%] Built target opencv
[ 24%] Built target raspicamera
[ 32%] Built target restclient
[ 36%] Built target ENCODE_LIBRARY
[ 36%] Built target rerun
[ 41%] Built target FILEWATCHER_LIBRARY
[ 42%] Built target EXECUTOR_LIBRARY
[ 46%] Built target TINYXML_LIBRARY
[ 60%] Built target KERBEROS_CORE
[ 61%] Built target MMAPGPIO_LIBRARY
[ 78%] Built target kerberosio
Linking CXX executable ../../test/bin/kerberos-test
/usr/bin/ld: cannot open output file ../../test/bin/kerberos-test: No such file or directory
collect2: error: ld returned 1 exit status
test/CMakeFiles/kerberos-test.dir/build.make:607: recipe for target '../test/bin/kerberos-test' failed
make[2]: *** [../test/bin/kerberos-test] Error 1
CMakeFiles/Makefile2:1536: recipe for target 'test/CMakeFiles/kerberos-test.dir/all' failed
make[1]: *** [test/CMakeFiles/kerberos-test.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by cedricve** [comment]
can you try sudo make?

**Comment by cedricve** [comment]
can you try 

> sudo make

**Comment by ypwu1** [comment]
Fantastic! issue solved.
