### ISSUE TITLE
Javascript error on dashboard

### ISSUE THREAD

**Issue by skududufru** [kerberos-io/machinery#52]
Hi !

As you can see in the picture, I got an issue when I go on the dashboard.
The four square are loading but nothing append.
Maybe it's because they aren't any movement ?

![capture](https://cloud.githubusercontent.com/assets/5992479/18129797/a075b3f2-6f8c-11e6-9927-0c827d441728.PNG)

**Comment by cedricve** [comment]
Hi @skududufru 

Indeed that's the reason, this will be fixed in next version.

**Comment by cedricve** [comment]
Fixed in release v2.1.0
