### ISSUE TITLE
V2 no longer working with my pi 3b onboard wifi

### ISSUE THREAD

**Issue by madpharmy** [kerberos-io/machinery#55]
v1 works just fine with my pi wifi installed with kios, but v2 set up the same always ends up with no device on wpa_supplicant

**Comment by cedricve** [comment]
thanks for the report, i'll check it myself.

**Comment by cedricve** [comment]
You're right, some firmware is missing for the new release. I'll add it and compile a new image. I'll let you know when it's done.

**Comment by cedricve** [comment]
@madpharmy I've uploaded a new image for v2.1.0 RPi3, can you please try again with this one. Please let me know if this solved your problem. Thanks!

**Comment by madpharmy** [comment]
this worked for me, thanks
