### ISSUE TITLE
File capture

### ISSUE THREAD

**Issue by JonasGroeger** [kerberos-io/machinery#59]
Hello!

I'm writing you because I have a use case in which the videos were taken without Kerberos. Now, I would like to see the movement in the videos without capturing from a camera but by just using the file.

Of course it has to do this faster than the capture, since the whole data is already in the file.

Looking at the source, I see that there is no FileCapture setting nor code for it. So I'm assuming this is not possible right now.

What would be the steps to have this and how would a contribution look like?

**Comment by cedricve** [comment]
Hello @JonasGroeger 

Yes it is possible, we have the VideoCapture device. You can specify the path to the video file.

![screen shot 2016-12-01 at 09 27 48](https://cloud.githubusercontent.com/assets/1546779/20786820/7c7dc4e4-b7a8-11e6-8494-118c8b253c91.png)

Hope this helps

**Comment by JonasGroeger** [comment]
@cedricve Is the video then played at normal speed or sped up?

**Comment by cedricve** [comment]
It depends on the machine you're running Kerberos.io and the resolution of the video. If kerberos.io can process faster than the FPS of your video, than yes otherwise no.

What are the specs of your video file? (FPS and resolution)

**Comment by JonasGroeger** [comment]
@cedricve Its a 1280x720 with 30FPS (15FPS, frames are doubled). I would be running Kerberos on a quite powerful machine.

**Comment by cedricve** [comment]
To be honest don't think you will be able to go faster than the video, with Kerberos.io.

**Comment by cedricve** [comment]
The difference between video files and a capture device (usb camera), is that each frame in the videofile will be processed. With a usb camera the frames which are stored in the buffer of the camera are processed. The usb camera clears it buffers so it shows nearly real time images.

**Comment by cedricve** [comment]
hey @JonasGroeger any update on this?

**Comment by JonasGroeger** [comment]
@cedricve The use case I had is no longer a thing, unfortunately.
