### ISSUE TITLE
Enhancement request - Output as video file

### ISSUE THREAD

**Issue by vgoncearencu** [kerberos-io/machinery#60]
Hello,
it would be great to have possibility if a motion detection is triggered to save that event not as a series of images but instead trigger a video record and save it to a file with possibility to view it from WebUI .

So from configuration page we could choose, output type as either:
- Image (snapshot)
or
- Video record

Why it should be implemented ?

1. There are times that an action takes like 2 minutes. By this time machinery creates hundreds of images . In order to view what happened from WebUI we have to click button "next" to get next image hundreds of time, in order to view what happened in reality. This creates discomfort :(

2. In OpenCV there is already "VideoWriter::VideoWriter" constructor that could be used for this. 
This constructor can create files in many formats including mpeg-1 and mjpg.
http://docs.opencv.org/3.0-beta/modules/videoio/doc/reading_and_writing_video.html#videowriter-videowriter

Let me know what do you think about this possible enhancement ?

Thank you,
Victor

**Comment by marksev1** [comment]
Maybe the images could still be used but in the WebUI there would be a slider to fast scroll through the images? Thus creating a video with sliding the slider faster :).  What do you think?

**Comment by cedricve** [comment]
Hello @vgoncearencu 

I've thought about this feature a lot, and the reason why I didn't developed is because I wasn't able to save the videofile with the correct FPS (performance of the machine to process the algorithms). It's a hard exercise, and requires a different approach..

But indeed it would be a nice feature.
Cédric

**Comment by cedricve** [comment]
@marksev1, problem is that loading all the images separately will request more bandwidth. At this moment the first 3 images are preloaded. I admit if there are a lot of images, it's a repetitive task.

**Comment by cedricve** [comment]
@vgoncearencu @marksev1 I'll see if I can make develop something clean for this. Probably I'll need help from an expert.

**Comment by cedricve** [comment]
Currently implementing the video feature, will release a develop version once I have a stable solution.

**Comment by vgoncearencu** [comment]
thank you guys you are the best!

**Comment by cedricve** [comment]
Video's will be displayed in the GUI like this, what do you think? A player will open once you've clicked on a camera icon.

![screen shot 2016-12-16 at 20 03 26](https://cloud.githubusercontent.com/assets/1546779/21274926/d2ca394e-c3ca-11e6-9e91-94894a729dcc.png)

**Comment by vgoncearencu** [comment]
Looks good. The player will have a start/stop/pause buttons ?

**Comment by cedricve** [comment]
yes @vgoncearencu 

![screen shot 2016-12-18 at 21 15 28](https://cloud.githubusercontent.com/assets/1546779/21296223/38ab5ebc-c567-11e6-814e-c1c5139bac12.png)

However when multiple videos are recorded as visualised above I would like to have a playlist as well. what do you think? 

![screen shot 2016-12-18 at 21 17 24](https://cloud.githubusercontent.com/assets/1546779/21296231/5f604d88-c567-11e6-8649-92adcf8af89d.png)

**Comment by vgoncearencu** [comment]
yes. That will make watching videos much easier.

**Comment by cedricve** [comment]
Update on player, now includes a playlist.

![screen shot 2016-12-21 at 09 44 27](https://cloud.githubusercontent.com/assets/1546779/21382649/2be63b00-c762-11e6-8ae1-d90fe5dec6e8.png)

**Comment by marksev1** [comment]
Its soo cool to watch the developement in realtime Cedric! :D

**Comment by cedricve** [comment]
Finished this feature, and added to develop branch. This will be integrated in next release. 

Features:
- Video and or Image can be saved.
- When only video's are saved, the first video in a sequence will be play automatically in the web interface.
- When more videos are saved in a sequence a playlist is available.
- Responsive support.

Results:

![2016-12-29 12_47_11](https://cloud.githubusercontent.com/assets/1546779/21543301/1c01a3aa-cdc5-11e6-912d-8f6a19254f24.gif)

![screen shot 2016-12-29 at 12 40 08](https://cloud.githubusercontent.com/assets/1546779/21543302/201bdc62-cdc5-11e6-93c5-57d1f38dc702.png)

**Comment by cedricve** [comment]
will be integrated in version 2.2.0
