### ISSUE TITLE
Does it run on other SBCs?

### ISSUE THREAD

**Issue by marksev1** [kerberos-io/machinery#61]
Hello, very nice project indeed!

I'm interested in running this on other SBCs, is there maybe a possibility of a ppa or something that is not directly tied with the Raspberry Pi's? For example Orange Pi PCs are now popular?

**Comment by cedricve** [comment]
Hey :) Yep you can follow the Raspbian installation for the Orange Pi.

**Comment by marksev1** [comment]
But which Rpi version would i choose so that I get the most correct .deb, should i use RPi2 or RPi3 deb for example?

**Comment by cedricve** [comment]
What are the specs of the OrangePi?

**Comment by marksev1** [comment]
Its Allwinner H3 cpu -> https://linux-sunxi.org/H3

Specs of Orange Pi PC board:
Specifications
SoC	H3 @ 1.3 GHz
DRAM	1GiB DDR3L (v1.2 K4B4G1646Q-HYK0, v1.3 K4B4G1646E-BYK0)
Power	DC 5V @ 2A (4.0mm/1.7mm barrel plug - centre positive)
or via GPIO header pins
Features
Video	HDMI (HDCP, CEC), CVBS
Audio	3.5 mm Jack, HDMI, Microphone
Network	10/100 Ethernet
Storage	µSD, 8GB eMMC on PC Plus
USB	3 USB 2.0 Host, 1 USB 2.0 OTG
Other	IR

**Comment by cedricve** [comment]
You can use the Raspberry Pi 2 debian file, give it a try.

**Comment by marksev1** [comment]
Need to first buy an IP-cam, but when I do I will for sure try it cedricve! Thanks! Will let you know how it goes and how we can later on add support for it if it doesn't work on first try.
