### ISSUE TITLE
Slack or IRC channel?

### ISSUE THREAD

**Issue by marksev1** [kerberos-io/machinery#63]
As the title said, would be nice to have it. I think this is such and important project that it would make sense.
 Close the issue if you feel its not needed.

**Comment by cedricve** [comment]
New collaboration platforms like slack and IRC are released every day. I don't think it will be useful to implement those API's. It would be better to support something like IFTTT or MQTT.

**Comment by marksev1** [comment]
No I meant for chat regarding developement :)

**Comment by cedricve** [comment]
Sorry my bad we have a channel on gitter. https://gitter.im/kerberos-io/hades
