### ISSUE TITLE
Weird colors from RPi Camera V2, possible white balance adjustment?

### ISSUE THREAD

**Issue by HanYangZhao** [kerberos-io/machinery#64]
The colors from the stream and images are weird. For some reason, the skin color is blue. This happens both with the NoIR V2 as well as the normal V2. Perhaps it's a white balance issue?

Thanks

**Comment by cedricve** [comment]
Are you using the raspbian images?

**Comment by HanYangZhao** [comment]
Yes I also tried compiling the latest version of the master branch but the results were the same

**Comment by cedricve** [comment]
Did you upgrade to latest firmware?

**Comment by HanYangZhao** [comment]
Yes did a sudo apt update and upgrade before compiling

**Comment by HanYangZhao** [comment]
3

**Comment by Whytehorse** [comment]
The V2 camera is much more sensitive than V1. You can tune the parameters in the uv4l conf file. I forget the name if it

**Comment by cedricve** [comment]
@HanYangZhao a bug in the raspicam library we are using, we will integrate the fix in next release.

**Comment by HanYangZhao** [comment]
Thanks. Is there a quick fix I can apply right now?
