### ISSUE TITLE
Condition/enabled => false ignored, keep capturing .

### ISSUE THREAD

**Issue by Naprosnia** [kerberos-io/machinery#91]
Everything is working properly, except the condition/enabled = false, which seems to be ignored, and continues to capture images and video.

Edit: Shutdown and  Reboot seem not to work either. I install kerberos on debian, following general installation guide.

**Comment by cedricve** [comment]
Hey @Naprosnia, how are you changing the condition enabled? Through the API, webinterface or XML config?
